- name: Apply Kubernetes config resources
  command: kubectl apply -f {{ item }}
  args:
    chdir: "{{ playbook_dir }}/../.."
  loop:
    - k8s/configmap.yaml
    - k8s/secret.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/hpa.yaml

